server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://notification-db:5432/notification
    username: notificationuser
    password: notificationpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      bootstrap-servers: kafka:9093
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Hata olduğunda durmasın diye ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        # --- KRİTİK AYARLAR ---
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        # Mapping: Gönderen Paket -> Alan (Notification) Paket
      # ... (diğer ayarlar)
        properties:
          spring.json.type.mapping: >
            com.example.UserMicroServiceProject.domain.event.UserRegisteredEvent:org.example.notification.dto.event.UserRegisteredEvent,
            com.example.order.order_service.application.dto.OrderCreatedEvent:org.example.notification.dto.event.OrderCreatedEvent,
            com.microservices.cart_service.Event.ItemAddedToCartEvent:org.example.notification.dto.event.ItemAddedToCartEvent
# Mail ayarları (Loglarda görmek için dummy ayarlar)
# Gerçek mail atmaması için serviste loglama yapması yeterli
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: testpassword